import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { FaProductHunt, FaTruckMoving } from 'react-icons/fa'
import { MdOutlineAttachMoney } from 'react-icons/md'

export default function Home(props) {
  return (
    <div>
      <Head>
        <title>Online Shopping for Tshirts, Mugs, Hoddies & Groceries at PlanetMarts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main h-full">
        <section className="text-gray-600 body-font">
          <div className="container px-5 py-5 mx-auto">
            <div className="flex flex-wrap-reverse w-full mb-20">
              <div className="lg:w-1/2 w-full mb-3 lg:mb-0">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">PlanetMarts Top Products</h1>
                <div className="h-1 w-20 bg-pink-500 rounded"></div>
              </div>
            </div>
            <div className="flex flex-wrap -m-4">
              {props.product.data.map((item) => {
                return (
                  <Link href={`/top-products/${item.attributes.Slug}`}>
                    <div className="xl:w-1/5 md:w-1/2 p-4 h-auto cursor-pointer">
                      <div className="bg-gray-100 p-6 rounded-lg">
                        <img className="h-full rounded w-full object-cover object-center mb-6" src={item.attributes.Image.data && item.attributes.Image.data.attributes.name} />
                          <h3 className="tracking-widest text-pink-500 text-xs font-medium title-font">{item.attributes.Category}</h3>
                          <h2 className="text-lg text-gray-900 font-medium title-font mb-4">{item.attributes.Name}</h2>
                          <p className="leading-relaxed text-base">₹{item.attributes.Price}</p>
                      </div>
                    </div>
                  </Link>
                )
              })}
            </div>
          </div>
        </section>
        <section className="text-gray-600 body-font overflow-y-hidden mb-5">
          <div className="container px-5 mx-auto">
            <div className="flex flex-wrap -m-4">
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500">
                    <FaProductHunt className="w-6 h-6" />
                  </div>
                  <h2 className="text-lg text-gray-900 font-medium title-font">Premium Products</h2>
                  <p className="leading-relaxed text-base">Our products give you 100% Quality</p>
                </div>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 mx-auto">
                    <FaTruckMoving className="w-6 h-6" />
                  </div>
                  <h2 className="text-lg text-gray-900 font-medium title-font mx-auto w-full">Free Shipping</h2>
                  <p className="leading-relaxed text-base mx-auto">We ship all over India for FREE.</p>
                </div>
              </div>
              <div className="xl:w-1/3 md:w-1/2 p-4">
                <div className="border border-gray-200 p-6 rounded-lg">
                  <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-pink-100 text-pink-500 mx-auto">
                    <MdOutlineAttachMoney className="w-6 h-6" />
                  </div>
                  <h2 className="text-lg text-gray-900 font-medium title-font mx-auto">Exciting Offers</h2>
                  <p className="leading-relaxed text-base mx-auto">We provide amazing offers & discounts on our products.</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  let headers = { Authorazition: "Bearer   2215d5dff7a6bb9939e33dad1ad72ae27eba9e9d61cb7f927adf8c51db0c0b343a9036b01254f45c418d6f337a9e019a01dd6dbb6b2137c4d81f5e5a648717e66361f3fd7bc79e7e6dd08b964744f37e73fca091ad67412da05430f12bab9a6593de0c962ab7785b5ec43ee592e55b87c102dabd05eb9f91f7fa74605be8acc2" }
  let a = await fetch("http://localhost:1337/api/top-products?populate=*", { headers: headers })
  let product = await a.json()
  return {
    props: { product: product }
  }
}
